site_name: AeroBeat Documentation
site_url: https://aerobeat-fitness.github.io/aerobeat-docs/
repo_url: https://github.com/AeroBeat-Fitness/aerobeat-docs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.top
  palette: 
    primary: teal
    accent: purple
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Licensing: licensing/overview.md
  - Release Notes: releases/changelog.md
  - Game Design:
    - Overview: gdd/concept.md
    - Art: 
      - Overview: gdd/art/overview.md
    - Gameplay:
      - Boxing: gdd/gameplay/boxing.md
      - Future Plans: gdd/gameplay/future-plans.md
    - Gamification:
      - Overview: gdd/gamification/overview.md
    - Input System:
      - Overview: gdd/input-system/agnostic-input.md
    - Modifiers:
      - Overview: gdd/modifiers/accessibility.md
      - Difficulty: gdd/modifiers/difficulty.md
    - Releases:
      - Community: gdd/releases/community.md
      - Stores & Arcades: gdd/releases/digital-stores-and-arcades.md
    - Roadmap:
      - Future Roadmap: gdd/roadmap/future-roadmap.md
    - User Content:
      - Overview: gdd/user-content/overview.md
      - Community Creations: gdd/user-content/community-creations.md
      - Policing Content: gdd/user-content/policing-content.md
  - Technical:
    - Architecture: architecture/architecture.md
    - Core Contracts: api/core/
    - Assembly: api/assembly/
    - Input Systems:
      - Camera (PC): api/inputs/mediapipe_python/
      - Camera (Mobile): api/inputs/mediapipe_native/
      - Joycon: api/inputs/joycon/
      - Keyboard: api/inputs/keyboard/
      - Controller: api/inputs/gamepad/
      - Mouse: api/inputs/mouse/
      - Touch: api/inputs/touch/
    - Features:
      - Boxing: api/features/boxing/
    - Assets:
      - Prototypes: api/assets/prototypes/
